# -*- coding: utf-8 -*-
"""Beginner level Text Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQZlwxERAsbxYbQ7ujJc39wx9bEbzO_y
"""

text = input("Enter text here: ")
len_text = print("length of text is: ",len(text))
count_words = print("The words in text is:",len(text.split()))
find_word = input("Enter word to find from text: ")
if find_word in text.split():
  print("Word is in text")
else:
  print("Word is not in text")